# Generated by Django 5.0 on 2024-01-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='mode_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
